current_dir := ${CURDIR}
TOP := top
SOURCES := ${current_dir}/picosoc_noflash.v \
           ${current_dir}/picorv32.v \
           ${current_dir}/simpleuart.v \
           ${current_dir}/progmem.v

SDC := ${current_dir}/picosoc.sdc

SOURCES += ${current_dir}/basys3.v
PCF := ${current_dir}/basys3.pcf

include ${current_dir}/common.mk
